@startuml
'https://plantuml.com/use-case-diagram

left to right direction

Actor Administrator as admin
Actor PowerUser as pw
Actor RoomOwner as ro

usecase "UC03: Access list of rooms" as UC3

admin --> UC3
pw --> UC3
ro --> UC3

@enduml