@startuml
'https://plantuml.com/use-case-diagram

left to right direction

Actor Administrator as admin
Actor PowerUser as pw
Actor RoomOwner as ro


usecase "UC06: Access list of devices" as UC6



ro --> UC6
admin --> UC6
pw --> UC6



@enduml