#
FROM maven:3.8.1-openjdk-17 AS build

ENV MAVEN_OPTS="-Xmx2g"

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

FROM tomcat:10.0

RUN mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/smarthome.war

EXPOSE 8080

CMD ["catalina.sh", "run"]