#To build the dist folder
#npm run build -- --mode production

FROM node:alpine AS build

WORKDIR /app

COPY ./frontendgrupo2/package*.json ./

RUN npm install

COPY ./frontendgrupo2 ./

RUN npm run build -- --mode production

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80