@startuml
'https://plantuml.com/sequence-diagram

autonumber

box "  <<system>> \n SmartHome"
    participant " <<container>> \n :Frontend" as frontend
    participant " <<container>> \n :Backend" as backend
    participant " <<container>> \n :WeatherService" as ws
end box



[o-> frontend: Get list of X

frontend->backend: GET /X

note right
  Get list of X.
  X can represent rooms, devices,
  sensors, actuators or sensor readings
end note

backend-->frontend: 200 - OK + body

[o<-- frontend: X list



@enduml