@startuml
'https://plantuml.com/use-case-diagram

left to right direction

Actor Administrator as admin


usecase "UC06: Access list of devices" as UC6
usecase "UC07: Add sensor to device" as UC7
usecase "Get list of sensor types" as UC103
usecase "Get list of sensor models" as UC104


UC7 --> UC104 #line.dashed : <<includes>>
UC104 --> UC103 #line.dashed : <<includes>>
UC7 --> UC6 #line.dashed : <<includes>>

admin --> UC7

@enduml