@startuml
'https://plantuml.com/component-diagram


component "<<system>> \n Smart Home" {



port port1
port port2
port port3

}

"REST API" -- port1
"SmartHome UI" -- port2

label "Weather API" as bb
port3 -u-( bb

@enduml